### ISSUE TITLE
Some details in this paper.

### ISSUE THREAD

**Issue by maogewudi007** [ruiyan1995/Region_Learner#2]
您好，文章arxiv版本上，有两个问题，期待作者解答一下：
1 Interaction操作，video输入的大小是：S\*T\*d； 输出的形状为什么变成：K\*T\*d？ 不是应该输入输出大小一致？
2 计算video和text相似度，video形状是K\*T\*d，text此时为 768 维度。计算相似度的时候，video和text大小不一致，那么具体是如何计算相似度的？

**Comment by ruiyan1995** [comment]
@maogewudi007 Thank you for your questions. Video feature Z should be K*T*d, that's a typo error. Before calculating the similarity, Z is fused into a single vector of 768 dimensions.

**Comment by maogewudi007** [comment]
Thank you!

**Comment by vateye** [comment]
> @maogewudi007 Thank you for your questions. Video feature Z should be K_T_d, that's a typo error. Before calculating the similarity, Z is fused into a single vector of 768 dimensions.

But in the code, I think you directly use the CLS token rather than the output from the RegionLearner?
