### ISSUE TITLE
Can’t reproduce the results

### ISSUE THREAD

**Issue by BlueCat7** [ruiyan1995/Region_Learner#3]
Dear author,
  I want to reproduce your paper results. I run the pre-training.sh, but the msrvtt zero-shot rank@1 only 10.7 not matched your result 22.2. Could you please share your pre-training log. I think it's useful for me to debug. Thanks!

**Comment by ruiyan1995** [comment]
Sure, I will update the code and example log in 2 days.

**Comment by BlueCat7** [comment]
> Sure, I will update the code and example log in 2 days.

Nice! Thank you very much!

**Comment by ruiyan1995** [comment]
pls check

**Comment by BlueCat7** [comment]
> pls check

OK，thanks!
